import singer
import json
import time
from singer import metadata
from datetime import datetime, timedelta
from google.ads.googleads.client import GoogleAdsClient
from google.ads.googleads.errors import GoogleAdsException
from .base import Base

LOGGER = singer.get_logger()

class Ads(Base):
    @property
    def name(self):
        return "ads"

    @property
    def key_properties(self):
        return ["resource_name"]

    @property
    def replication_key(self):
        return None

    @property
    def replication_method(self):
        return "FULL_TABLE"

    def gen_records(self, service, customer_id):
        query = """
            SELECT
                ad_group_ad.action_items,
                ad_group_ad.ad.added_by_google_ads,
                ad_group_ad.ad.app_ad.descriptions,
                ad_group_ad.ad.app_ad.headlines,
                ad_group_ad.ad.app_ad.html5_media_bundles,
                ad_group_ad.ad.app_ad.images,
                ad_group_ad.ad.app_ad.mandatory_ad_text,
                ad_group_ad.ad.app_ad.youtube_videos,
                ad_group_ad.ad.app_engagement_ad.descriptions,
                ad_group_ad.ad.app_engagement_ad.headlines,
                ad_group_ad.ad.app_engagement_ad.images,
                ad_group_ad.ad.app_engagement_ad.videos,
                ad_group_ad.ad.app_pre_registration_ad.descriptions,
                ad_group_ad.ad.app_pre_registration_ad.headlines,
                ad_group_ad.ad.app_pre_registration_ad.images,
                ad_group_ad.ad.app_pre_registration_ad.youtube_videos,
                ad_group_ad.ad.call_ad.business_name,
                ad_group_ad.ad.call_ad.call_tracked,
                ad_group_ad.ad.call_ad.conversion_action,
                ad_group_ad.ad.call_ad.conversion_reporting_state,
                ad_group_ad.ad.call_ad.country_code,
                ad_group_ad.ad.call_ad.description1,
                ad_group_ad.ad.call_ad.description2,
                ad_group_ad.ad.call_ad.disable_call_conversion,
                ad_group_ad.ad.call_ad.headline1,
                ad_group_ad.ad.call_ad.headline2,
                ad_group_ad.ad.call_ad.path1,
                ad_group_ad.ad.call_ad.path2,
                ad_group_ad.ad.call_ad.phone_number,
                ad_group_ad.ad.call_ad.phone_number_verification_url,
                ad_group_ad.ad.device_preference,
                ad_group_ad.ad.discovery_carousel_ad.business_name,
                ad_group_ad.ad.discovery_carousel_ad.call_to_action_text,
                ad_group_ad.ad.discovery_carousel_ad.carousel_cards,
                ad_group_ad.ad.discovery_carousel_ad.description,
                ad_group_ad.ad.discovery_carousel_ad.headline,
                ad_group_ad.ad.discovery_carousel_ad.logo_image,
                ad_group_ad.ad.discovery_multi_asset_ad.business_name,
                ad_group_ad.ad.discovery_multi_asset_ad.call_to_action_text,
                ad_group_ad.ad.discovery_multi_asset_ad.descriptions,
                ad_group_ad.ad.discovery_multi_asset_ad.headlines,
                ad_group_ad.ad.discovery_multi_asset_ad.lead_form_only,
                ad_group_ad.ad.discovery_multi_asset_ad.logo_images,
                ad_group_ad.ad.discovery_multi_asset_ad.marketing_images,
                ad_group_ad.ad.discovery_multi_asset_ad.portrait_marketing_images,
                ad_group_ad.ad.discovery_multi_asset_ad.square_marketing_images,
                ad_group_ad.ad.display_upload_ad.display_upload_product_type,
                ad_group_ad.ad.display_upload_ad.media_bundle,
                ad_group_ad.ad.display_url,
                ad_group_ad.ad.expanded_dynamic_search_ad.description,
                ad_group_ad.ad.expanded_dynamic_search_ad.description2,
                ad_group_ad.ad.expanded_text_ad.description,
                ad_group_ad.ad.expanded_text_ad.description2,
                ad_group_ad.ad.expanded_text_ad.headline_part1,
                ad_group_ad.ad.expanded_text_ad.headline_part2,
                ad_group_ad.ad.expanded_text_ad.headline_part3,
                ad_group_ad.ad.expanded_text_ad.path1,
                ad_group_ad.ad.expanded_text_ad.path2,
                ad_group_ad.ad.final_app_urls,
                ad_group_ad.ad.final_mobile_urls,
                ad_group_ad.ad.final_url_suffix,
                ad_group_ad.ad.final_urls,
                ad_group_ad.ad.hotel_ad,
                ad_group_ad.ad.id,
                ad_group_ad.ad.image_ad.image_url,
                ad_group_ad.ad.image_ad.mime_type,
                ad_group_ad.ad.image_ad.name,
                ad_group_ad.ad.image_ad.pixel_height,
                ad_group_ad.ad.image_ad.pixel_width,
                ad_group_ad.ad.image_ad.preview_image_url,
                ad_group_ad.ad.image_ad.preview_pixel_height,
                ad_group_ad.ad.image_ad.preview_pixel_width,
                ad_group_ad.ad.legacy_app_install_ad,
                ad_group_ad.ad.legacy_responsive_display_ad.accent_color,
                ad_group_ad.ad.legacy_responsive_display_ad.allow_flexible_color,
                ad_group_ad.ad.legacy_responsive_display_ad.business_name,
                ad_group_ad.ad.legacy_responsive_display_ad.call_to_action_text,
                ad_group_ad.ad.legacy_responsive_display_ad.description,
                ad_group_ad.ad.legacy_responsive_display_ad.format_setting,
                ad_group_ad.ad.legacy_responsive_display_ad.logo_image,
                ad_group_ad.ad.legacy_responsive_display_ad.long_headline,
                ad_group_ad.ad.legacy_responsive_display_ad.main_color,
                ad_group_ad.ad.legacy_responsive_display_ad.marketing_image,
                ad_group_ad.ad.legacy_responsive_display_ad.price_prefix,
                ad_group_ad.ad.legacy_responsive_display_ad.promo_text,
                ad_group_ad.ad.legacy_responsive_display_ad.short_headline,
                ad_group_ad.ad.legacy_responsive_display_ad.square_logo_image,
                ad_group_ad.ad.legacy_responsive_display_ad.square_marketing_image,
                ad_group_ad.ad.local_ad.call_to_actions,
                ad_group_ad.ad.local_ad.descriptions,
                ad_group_ad.ad.local_ad.headlines,
                ad_group_ad.ad.local_ad.logo_images,
                ad_group_ad.ad.local_ad.marketing_images,
                ad_group_ad.ad.local_ad.path1,
                ad_group_ad.ad.local_ad.path2,
                ad_group_ad.ad.local_ad.videos,
                ad_group_ad.ad.name,
                ad_group_ad.ad.resource_name,
                ad_group_ad.ad.responsive_display_ad.accent_color,
                ad_group_ad.ad.responsive_display_ad.allow_flexible_color,
                ad_group_ad.ad.responsive_display_ad.business_name,
                ad_group_ad.ad.responsive_display_ad.call_to_action_text,
                ad_group_ad.ad.responsive_display_ad.control_spec.enable_asset_enhancements,
                ad_group_ad.ad.responsive_display_ad.control_spec.enable_autogen_video,
                ad_group_ad.ad.responsive_display_ad.descriptions,
                ad_group_ad.ad.responsive_display_ad.format_setting,
                ad_group_ad.ad.responsive_display_ad.headlines,
                ad_group_ad.ad.responsive_display_ad.logo_images,
                ad_group_ad.ad.responsive_display_ad.long_headline,
                ad_group_ad.ad.responsive_display_ad.main_color,
                ad_group_ad.ad.responsive_display_ad.marketing_images,
                ad_group_ad.ad.responsive_display_ad.price_prefix,
                ad_group_ad.ad.responsive_display_ad.promo_text,
                ad_group_ad.ad.responsive_display_ad.square_logo_images,
                ad_group_ad.ad.responsive_display_ad.square_marketing_images,
                ad_group_ad.ad.responsive_display_ad.youtube_videos,
                ad_group_ad.ad.responsive_search_ad.descriptions,
                ad_group_ad.ad.responsive_search_ad.headlines,
                ad_group_ad.ad.responsive_search_ad.path1,
                ad_group_ad.ad.responsive_search_ad.path2,
                ad_group_ad.ad.shopping_comparison_listing_ad.headline,
                ad_group_ad.ad.shopping_product_ad,
                ad_group_ad.ad.shopping_smart_ad,
                ad_group_ad.ad.smart_campaign_ad.descriptions,
                ad_group_ad.ad.smart_campaign_ad.headlines,
                ad_group_ad.ad.system_managed_resource_source,
                ad_group_ad.ad.text_ad.description1,
                ad_group_ad.ad.text_ad.description2,
                ad_group_ad.ad.text_ad.headline,
                ad_group_ad.ad.tracking_url_template,
                ad_group_ad.ad.travel_ad,
                ad_group_ad.ad.type,
                ad_group_ad.ad.url_collections,
                ad_group_ad.ad.url_custom_parameters,
                ad_group_ad.ad.video_ad.bumper.action_button_label,
                ad_group_ad.ad.video_ad.bumper.action_headline,
                ad_group_ad.ad.video_ad.in_feed.description1,
                ad_group_ad.ad.video_ad.in_feed.description2,
                ad_group_ad.ad.video_ad.in_feed.headline,
                ad_group_ad.ad.video_ad.in_feed.thumbnail,
                ad_group_ad.ad.video_ad.in_stream.action_button_label,
                ad_group_ad.ad.video_ad.in_stream.action_headline,
                ad_group_ad.ad.video_ad.non_skippable.action_button_label,
                ad_group_ad.ad.video_ad.non_skippable.action_headline,
                ad_group_ad.ad.video_ad.out_stream.description,
                ad_group_ad.ad.video_ad.out_stream.headline,
                ad_group_ad.ad.video_responsive_ad.breadcrumb1,
                ad_group_ad.ad.video_responsive_ad.breadcrumb2,
                ad_group_ad.ad.video_responsive_ad.call_to_actions,
                ad_group_ad.ad.video_responsive_ad.companion_banners,
                ad_group_ad.ad.video_responsive_ad.descriptions,
                ad_group_ad.ad.video_responsive_ad.headlines,
                ad_group_ad.ad.video_responsive_ad.long_headlines,
                ad_group_ad.ad.video_responsive_ad.videos,
                ad_group_ad.ad_group,
                ad_group.campaign,
                ad_group_ad.ad_strength,
                ad_group_ad.labels,
                ad_group_ad.policy_summary.approval_status,
                ad_group_ad.policy_summary.policy_topic_entries,
                ad_group_ad.policy_summary.review_status,
                ad_group_ad.resource_name,
                ad_group_ad.status,
                customer.id
            FROM ad_group_ad
        """

        resp = service.search_stream(customer_id=customer_id, query=query)

        for batch in resp:
            for row in batch.results:
                ad = row.ad_group_ad
                ada = row.ad_group_ad.ad
                yield {
                    "name": ada.name,
                    "resource_name": ada.resource_name,
                    "id": ada.id,
                    "ad_group": ad.ad_group,
                    "campaign": row.ad_group.campaign,
                    "ad_group_id": int(ad.ad_group.split("/adGroups/")[1]),
                    "campaign_id": int(row.ad_group.campaign.split("/campaigns/")[1]),
                    "action_items": ad.action_items,
                    "added_by_google_ads": ada.added_by_google_ads,
                    "app_ad__descriptions": ada.app_ad.descriptions,
                    "app_ad__headlines": ada.app_ad.headlines,
                    "app_ad__html5_media_bundles": ada.app_ad.html5_media_bundles,
                    "app_ad__images": ada.app_ad.images,
                    "app_ad__mandatory_ad_text": ada.app_ad.mandatory_ad_text,
                    "app_ad__youtube_videos": ada.app_ad.youtube_videos,
                    "app_engagement_ad__descriptions": ada.app_engagement_ad.descriptions,
                    "app_engagement_ad__headlines": ada.app_engagement_ad.headlines,
                    "app_engagement_ad__images": ada.app_engagement_ad.images,
                    "app_engagement_ad__videos": ada.app_engagement_ad.videos,
                    "app_pre_registration_ad__descriptions": ada.app_pre_registration_ad.descriptions,
                    "app_pre_registration_ad__headlines": ada.app_pre_registration_ad.headlines,
                    "app_pre_registration_ad__images": ada.app_pre_registration_ad.images,
                    "app_pre_registration_ad__youtube_videos": ada.app_pre_registration_ad.youtube_videos,
                    "call_ad__business_name": ada.call_ad.business_name,
                    "call_ad__call_tracked": ada.call_ad.call_tracked,
                    "call_ad__conversion_action": ada.call_ad.conversion_action,
                    "call_ad__conversion_reporting_state": ada.call_ad.conversion_reporting_state,
                    "call_ad__country_code": ada.call_ad.country_code,
                    "call_ad__description1": ada.call_ad.description1,
                    "call_ad__description2": ada.call_ad.description2,
                    "call_ad__disable_call_conversion": ada.call_ad.disable_call_conversion,
                    "call_ad__headline1": ada.call_ad.headline1,
                    "call_ad__headline2": ada.call_ad.headline2,
                    "call_ad__path1": ada.call_ad.path1,
                    "call_ad__path2": ada.call_ad.path2,
                    "call_ad__phone_number": ada.call_ad.phone_number,
                    "call_ad__phone_number_verification_url": ada.call_ad.phone_number_verification_url,
                    "device_preference": ada.device_preference,
                    "discovery_carousel_ad__business_name": ada.discovery_carousel_ad.business_name,
                    "discovery_carousel_ad__call_to_action_text": ada.discovery_carousel_ad.call_to_action_text,
                    "discovery_carousel_ad__carousel_cards": ada.discovery_carousel_ad.carousel_cards,
                    "discovery_carousel_ad__description": ada.discovery_carousel_ad.description,
                    "discovery_carousel_ad__headline": ada.discovery_carousel_ad.headline,
                    "discovery_carousel_ad__logo_image": ada.discovery_carousel_ad.logo_image,
                    "discovery_multi_asset_ad__business_name": ada.discovery_multi_asset_ad.business_name,
                    "discovery_multi_asset_ad__call_to_action_text": ada.discovery_multi_asset_ad.call_to_action_text,
                    "discovery_multi_asset_ad__descriptions": ada.discovery_multi_asset_ad.descriptions,
                    "discovery_multi_asset_ad__headlines": ada.discovery_multi_asset_ad.headlines,
                    "discovery_multi_asset_ad__lead_form_only": ada.discovery_multi_asset_ad.lead_form_only,
                    "discovery_multi_asset_ad__logo_images": ada.discovery_multi_asset_ad.logo_images,
                    "discovery_multi_asset_ad__marketing_images": ada.discovery_multi_asset_ad.marketing_images,
                    "discovery_multi_asset_ad__portrait_marketing_images": ada.discovery_multi_asset_ad.portrait_marketing_images,
                    "discovery_multi_asset_ad__square_marketing_images": ada.discovery_multi_asset_ad.square_marketing_images,
                    "display_upload_ad__display_upload_product_type": ada.display_upload_ad.display_upload_product_type,
                    "display_upload_ad__media_bundle": ada.display_upload_ad.media_bundle,
                    "display_url": ada.display_url,
                    "expanded_dynamic_search_ad__description": ada.expanded_dynamic_search_ad.description,
                    "expanded_dynamic_search_ad__description2": ada.expanded_dynamic_search_ad.description2,
                    "expanded_text_ad__description": ada.expanded_text_ad.description,
                    "expanded_text_ad__description2": ada.expanded_text_ad.description2,
                    "expanded_text_ad__headline_part1": ada.expanded_text_ad.headline_part1,
                    "expanded_text_ad__headline_part2": ada.expanded_text_ad.headline_part2,
                    "expanded_text_ad__headline_part3": ada.expanded_text_ad.headline_part3,
                    "expanded_text_ad__path1": ada.expanded_text_ad.path1,
                    "expanded_text_ad__path2": ada.expanded_text_ad.path2,
                    "final_app_urls": ada.final_app_urls,
                    "final_mobile_urls": ada.final_mobile_urls,
                    "final_url_suffix": ada.final_url_suffix,
                    "final_urls": ada.final_urls,
                    "hotel_ad": ada.hotel_ad,
                    "image_ad__image_url": ada.image_ad.image_url,
                    "image_ad__mime_type": ada.image_ad.mime_type,
                    "image_ad__name": ada.image_ad.name,
                    "image_ad__pixel_height": ada.image_ad.pixel_height,
                    "image_ad__pixel_width": ada.image_ad.pixel_width,
                    "image_ad__preview_image_url": ada.image_ad.preview_image_url,
                    "image_ad__preview_pixel_height": ada.image_ad.preview_pixel_height,
                    "image_ad__preview_pixel_width": ada.image_ad.preview_pixel_width,
                    "legacy_app_install_ad": ada.legacy_app_install_ad,
                    "legacy_responsive_display_ad__accent_color": ada.legacy_responsive_display_ad.accent_color,
                    "legacy_responsive_display_ad__allow_flexible_color": ada.legacy_responsive_display_ad.allow_flexible_color,
                    "legacy_responsive_display_ad__business_name": ada.legacy_responsive_display_ad.business_name,
                    "legacy_responsive_display_ad__call_to_action_text": ada.legacy_responsive_display_ad.call_to_action_text,
                    "legacy_responsive_display_ad__description": ada.legacy_responsive_display_ad.description,
                    "legacy_responsive_display_ad__format_setting": ada.legacy_responsive_display_ad.format_setting,
                    "legacy_responsive_display_ad__logo_image": ada.legacy_responsive_display_ad.logo_image,
                    "legacy_responsive_display_ad__long_headline": ada.legacy_responsive_display_ad.long_headline,
                    "legacy_responsive_display_ad__main_color": ada.legacy_responsive_display_ad.main_color,
                    "legacy_responsive_display_ad__marketing_image": ada.legacy_responsive_display_ad.marketing_image,
                    "legacy_responsive_display_ad__price_prefix": ada.legacy_responsive_display_ad.price_prefix,
                    "legacy_responsive_display_ad__promo_text": ada.legacy_responsive_display_ad.promo_text,
                    "legacy_responsive_display_ad__short_headline": ada.legacy_responsive_display_ad.short_headline,
                    "legacy_responsive_display_ad__square_logo_image": ada.legacy_responsive_display_ad.square_logo_image,
                    "legacy_responsive_display_ad__square_marketing_image": ada.legacy_responsive_display_ad.square_marketing_image,
                    "local_ad__call_to_actions": ada.local_ad.call_to_actions,
                    "local_ad__descriptions": ada.local_ad.descriptions,
                    "local_ad__headlines": ada.local_ad.headlines,
                    "local_ad__logo_images": ada.local_ad.logo_images,
                    "local_ad__marketing_images": ada.local_ad.marketing_images,
                    "local_ad__path1": ada.local_ad.path1,
                    "local_ad__path2": ada.local_ad.path2,
                    "local_ad__videos": ada.local_ad.videos,
                    "responsive_display_ad__accent_color": ada.responsive_display_ad.accent_color,
                    "responsive_display_ad__allow_flexible_color": ada.responsive_display_ad.allow_flexible_color,
                    "responsive_display_ad__business_name": ada.responsive_display_ad.business_name,
                    "responsive_display_ad__call_to_action_text": ada.responsive_display_ad.call_to_action_text,
                    "responsive_display_ad__control_spec__enable_asset_enhancements": ada.responsive_display_ad.control_spec.enable_asset_enhancements,
                    "responsive_display_ad__control_spec__enable_autogen_video": ada.responsive_display_ad.control_spec.enable_autogen_video,
                    "responsive_display_ad__descriptions": ada.responsive_display_ad.descriptions,
                    "responsive_display_ad__format_setting": ada.responsive_display_ad.format_setting,
                    "responsive_display_ad__headlines": ada.responsive_display_ad.headlines,
                    "responsive_display_ad__logo_images": ada.responsive_display_ad.logo_images,
                    "responsive_display_ad__long_headline": ada.responsive_display_ad.long_headline,
                    "responsive_display_ad__main_color": ada.responsive_display_ad.main_color,
                    "responsive_display_ad__marketing_images": ada.responsive_display_ad.marketing_images,
                    "responsive_display_ad__price_prefix": ada.responsive_display_ad.price_prefix,
                    "responsive_display_ad__promo_text": ada.responsive_display_ad.promo_text,
                    "responsive_display_ad__square_logo_images": ada.responsive_display_ad.square_logo_images,
                    "responsive_display_ad__square_marketing_images": ada.responsive_display_ad.square_marketing_images,
                    "responsive_display_ad__youtube_videos": ada.responsive_display_ad.youtube_videos,
                    "responsive_search_ad__descriptions": ada.responsive_search_ad.descriptions,
                    "responsive_search_ad__headlines": ada.responsive_search_ad.headlines,
                    "responsive_search_ad__path1": ada.responsive_search_ad.path1,
                    "responsive_search_ad__path2": ada.responsive_search_ad.path2,
                    "shopping_comparison_listing_ad__headline": ada.shopping_comparison_listing_ad.headline,
                    "shopping_product_ad": ada.shopping_product_ad,
                    "shopping_smart_ad": ada.shopping_smart_ad,
                    "smart_campaign_ad__descriptions": ada.smart_campaign_ad.descriptions,
                    "smart_campaign_ad__headlines": ada.smart_campaign_ad.headlines,
                    "system_managed_resource_source": ada.system_managed_resource_source,
                    "text_ad__description1": ada.text_ad.description1,
                    "text_ad__description2": ada.text_ad.description2,
                    "text_ad__headline": ada.text_ad.headline,
                    "tracking_url_template": ada.tracking_url_template,
                    "travel_ad": ada.travel_ad,
                    "type": str(ada.type_).lower(),
                    "url_collections": ada.url_collections,
                    "url_custom_parameters": ada.url_custom_parameters,
                    "video_ad__bumper__action_button_label": ada.video_ad.bumper.action_button_label,
                    "video_ad__bumper__action_headline": ada.video_ad.bumper.action_headline,
                    "video_ad__in_feed__description1": ada.video_ad.in_feed.description1,
                    "video_ad__in_feed__description2": ada.video_ad.in_feed.description2,
                    "video_ad__in_feed__headline": ada.video_ad.in_feed.headline,
                    "video_ad__in_feed__thumbnail": ada.video_ad.in_feed.thumbnail,
                    "video_ad__in_stream__action_button_label": ada.video_ad.in_stream.action_button_label,
                    "video_ad__in_stream__action_headline": ada.video_ad.in_stream.action_headline,
                    "video_ad__non_skippable__action_button_label": ada.video_ad.non_skippable.action_button_label,
                    "video_ad__non_skippable__action_headline": ada.video_ad.non_skippable.action_headline,
                    "video_ad__out_stream__description": ada.video_ad.out_stream.description,
                    "video_ad__out_stream__headline": ada.video_ad.out_stream.headline,
                    "video_responsive_ad__breadcrumb1": ada.video_responsive_ad.breadcrumb1,
                    "video_responsive_ad__breadcrumb2": ada.video_responsive_ad.breadcrumb2,
                    "video_responsive_ad__call_to_actions": ada.video_responsive_ad.call_to_actions,
                    "video_responsive_ad__companion_banners": ada.video_responsive_ad.companion_banners,
                    "video_responsive_ad__descriptions": ada.video_responsive_ad.descriptions,
                    "video_responsive_ad__headlines": ada.video_responsive_ad.headlines,
                    "video_responsive_ad__long_headlines": ada.video_responsive_ad.long_headlines,
                    "video_responsive_ad__videos": ada.video_responsive_ad.videos,
                    "ad_strength": ad.ad_strength,
                    "labels": list(ad.labels),
                    "policy_summary__approval_status": ad.policy_summary.approval_status,
                    "policy_summary__policy_topic_entries": ad.policy_summary.policy_topic_entries,
                    "policy_summary__review_status": ad.policy_summary.review_status,
                    "status": ad.status,
                    "customer_id": row.customer.id,
                }

            time.sleep(5)
